In [1]:
import pandas as pd
import json
from pandas import json_normalize

In [2]:
data = 'D:\\becode_projects\\ANT-Theano-3-34\\additional_resources\\datasets\\steam scrape\\database.json'

df = pd.read_json(data).T

df

,type,name,steam_appid,required_age,is_free,detailed_description,about_the_game,short_description,supported_languages,header_image,...,total_reviews,controller_support,dlc,demos,recommendations,achievements,reviews,ext_user_account_notice,metacritic,drm_notice
1198490,game,All That Remains: Part 1,1198490,0,False,“Duncan Price is paranoid” they used to say. H...,“Duncan Price is paranoid” they used to say. H...,“Duncan Price is paranoid” they used to say. H...,"English<strong>*</strong>, French, Italian, Ge...",https://cdn.akamai.steamstatic.com/steam/apps/...,...,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1198510,game,Paperball,1198510,0,False,It's time to get rolling!<br><br>Navigate tric...,It's time to get rolling!<br><br>Navigate tric...,It's time to get rolling! Navigate tricky pass...,"English<strong>*</strong>, German, Japanese, D...",https://cdn.akamai.steamstatic.com/steam/apps/...,...,134,full,"[1209620, 1209621, 1285150]","[{'appid': 1219680, 'description': ''}]",{'total': 143},"{'total': 37, 'highlighted': [{'name': 'Ready ...",NaN,NaN,NaN,NaN
1198550,game,Moderium,1198550,0,False,Moderium is a Wave-Based Isometric Action Role...,Moderium is a Wave-Based Isometric Action Role...,Conquer waves of encroaching enemies in this A...,English<strong>*</strong><br><strong>*</strong...,https://cdn.akamai.steamstatic.com/steam/apps/...,...,1,NaN,NaN,"[{'appid': 1220740, 'description': ''}]",NaN,NaN,NaN,NaN,NaN,NaN
1198600,game,Pizza Time Explosion,1198600,0,False,"<img src=""https://cdn.akamai.steamstatic.com/s...","<img src=""https://cdn.akamai.steamstatic.com/s...",Welcome to the Pizza Dimension!,English,https://cdn.akamai.steamstatic.com/steam/apps/...,...,18,full,[1220660],NaN,NaN,"{'total': 32, 'highlighted': [{'name': 'Pizza ...",NaN,NaN,NaN,NaN
1198630,game,Customer Cums First!,1198630,0,False,"<img src=""https://cdn.akamai.steamstatic.com/s...","<img src=""https://cdn.akamai.steamstatic.com/s...",It's just like any other shopping district in ...,English,https://cdn.akamai.steamstatic.com/steam/apps/...,...,10,NaN,NaN,NaN,NaN,"{'total': 18, 'highlighted': [{'name': 'Now th...",NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1113770,game,Lunch A Palooza,1113770,0,False,"<img src=""https://cdn.akamai.steamstatic.com/s...","<img src=""https://cdn.akamai.steamstatic.com/s...",Lunch A Palooza is a game for everyone! With i...,"English, French, Italian, German, Spanish - Sp...",https://cdn.akamai.steamstatic.com/steam/apps/...,...,13,full,NaN,NaN,NaN,"{'total': 21, 'highlighted': [{'name': 'You go...",NaN,NaN,NaN,NaN
1113780,game,Uncharted Tides: Port Royal,1113780,0,False,"Mason Owens is missing for decades, and yet hi...","Mason Owens is missing for decades, and yet hi...",Dead men tell no tales! And tales about an inf...,"English<strong>*</strong>, French, Italian, Ge...",https://cdn.akamai.steamstatic.com/steam/apps/...,...,30,NaN,NaN,NaN,NaN,"{'total': 22, 'highlighted': [{'name': 'Cursed...",NaN,NaN,NaN,NaN
1113000,game,Persona 4 Golden,1113000,0,False,"<h1>Digital Deluxe Edition</h1><p><img src=""ht...","<img src=""https://cdn.akamai.steamstatic.com/s...",A coming of age story that sets the protagonis...,"English<strong>*</strong>, Japanese<strong>*</...",https://cdn.akamai.steamstatic.com/steam/apps/...,...,29998,full,NaN,NaN,{'total': 42884},"{'total': 50, 'highlighted': [{'name': 'Golden...",“You can now enjoy the masterpiece in its best...,NaN,NaN,Denuvo Anti-tamper
1113060,game,Magic Farm 3: The Ice Danger,1113060,0,False,Magic Farm 3: The Ice Danger is an adventure a...,Magic Farm 3: The Ice Danger is an adventure a...,&quot;Magic Farm 3: The Ice Danger&quot; is a ...,English,https://cdn.akamai.steamstatic.com/steam/apps/...,...,4,NaN,NaN,"[{'appid': 1113180, 'description': ''}]",NaN,"{'total': 27, 'highlighted': [{'name': 'Insect...",NaN,NaN,NaN,NaN
1113110,game,The Stranger: Interactive Film,1113110,0,False,- You decide the course of story!<br />\r\n- I...,- You decide the course of story!<br />\r\n- I...,The Story: Your wife died in a boat accident. ...,English<strong>*</strong><br><strong>*</strong...,https://cdn.akamai.steamstatic.com/steam/apps/...,...,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4625 entries, 1198490 to 1113110
Data columns (total 44 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   type                     4625 non-null   object
 1   name                     4625 non-null   object
 2   steam_appid              4625 non-null   object
 3   required_age             4625 non-null   object
 4   is_free                  4625 non-null   object
 5   detailed_description     4625 non-null   object
 6   about_the_game           4625 non-null   object
 7   short_description        4625 non-null   object
 8   supported_languages      4625 non-null   object
 9   header_image             4625 non-null   object
 10  website                  2952 non-null   object
 11  pc_requirements          4625 non-null   object
 12  mac_requirements         4625 non-null   object
 13  linux_requirements       4625 non-null   object
 14  legal_notice             1569 non-null   object
 15  developers               4622 non-null   object
 16  publishers               4625 non-null   object
 17  price_overview           4253 non-null   object
 18  packages                 4289 non-null   object
 19  package_groups           4625 non-null   object
 20  platforms                4625 non-null   object
 21  categories               4556 non-null   object
 22  genres                   4622 non-null   object
 23  screenshots              4623 non-null   object
 24  movies                   4546 non-null   object
 25  release_date             4625 non-null   object
 26  support_info             4625 non-null   object
 27  background               4625 non-null   object
 28  content_descriptors      4625 non-null   object
 29  num_reviews              4625 non-null   object
 30  review_score             4625 non-null   object
 31  review_score_desc        4625 non-null   object
 32  total_positive           4625 non-null   object
 33  total_negative           4625 non-null   object
 34  total_reviews            4625 non-null   object
 35  controller_support       1163 non-null   object
 36  dlc                      967 non-null    object
 37  demos                    394 non-null    object
 38  recommendations          1134 non-null   object
 39  achievements             2872 non-null   object
 40  reviews                  883 non-null    object
 41  ext_user_account_notice  64 non-null     object
 42  metacritic               278 non-null    object
 43  drm_notice               15 non-null     object
dtypes: object(44)
memory usage: 1.7+ MB

In [4]:
df.required_age.unique()

array([0, '16', '18', '12', '17', '13', '1', '15', '10', '7'],
      dtype=object)

In [5]:
df['is_free'].unique()

array([False, True], dtype=object)

In [6]:
df['supported_languages'].unique()

array(['English<strong>*</strong>, French, Italian, German, Spanish - Spain<br><strong>*</strong>languages with full audio support',
       'English<strong>*</strong>, German, Japanese, Dutch<br><strong>*</strong>languages with full audio support',
       'English<strong>*</strong><br><strong>*</strong>languages with full audio support',
       ...,
       'English, French, Italian, German, Spanish - Spain, Japanese, Russian, Simplified Chinese, Traditional Chinese',
       'English, French, Italian, German, Spanish - Spain, Spanish - Latin America',
       'English<strong>*</strong>, Japanese<strong>*</strong>, Korean, Traditional Chinese<br><strong>*</strong>languages with full audio support'],
      dtype=object)

In [7]:
df[['price_overview']]

                                            price_overview
1198490  {'currency': 'EUR', 'initial': 239, 'final': 2...
1198510  {'currency': 'EUR', 'initial': 999, 'final': 9...
1198550  {'currency': 'EUR', 'initial': 79, 'final': 79...
1198600  {'currency': 'EUR', 'initial': 499, 'final': 4...
1198630  {'currency': 'EUR', 'initial': 999, 'final': 9...
...                                                    ...
1113770  {'currency': 'EUR', 'initial': 1079, 'final': ...
1113780  {'currency': 'EUR', 'initial': 1499, 'final': ...
1113000  {'currency': 'EUR', 'initial': 1999, 'final': ...
1113060  {'currency': 'EUR', 'initial': 1679, 'final': ...
1113110  {'currency': 'EUR', 'initial': 659, 'final': 6...

[4625 rows x 1 columns]

In [8]:
df[['genres']]

                                                    genres
1198490         [{'id': '25', 'description': 'Adventure'}]
1198510  [{'id': '1', 'description': 'Action'}, {'id': ...
1198550  [{'id': '1', 'description': 'Action'}, {'id': ...
1198600  [{'id': '1', 'description': 'Action'}, {'id': ...
1198630             [{'id': '4', 'description': 'Casual'}]
...                                                    ...
1113770  [{'id': '1', 'description': 'Action'}, {'id': ...
1113780  [{'id': '25', 'description': 'Adventure'}, {'i...
1113000                [{'id': '3', 'description': 'RPG'}]
1113060  [{'id': '4', 'description': 'Casual'}, {'id': ...
1113110  [{'id': '1', 'description': 'Action'}, {'id': ...

[4625 rows x 1 columns]

In [9]:
df['review_score'].unique()

array([0, 8, 7, 6, 5, 4, 9, 3, 2], dtype=object)

In [10]:
# df_normalized = pd.json_normalize(data)
# df_normalized

In [11]:
# import json
# # load data using Python JSON module
# with open(data,'r') as f:
#     data_json = json.load(f)
# # Flatten data
# df_nested_dict = pd.json_normalize(data_json, record_path =['genres'])

In [12]:
# import json 
# import pandas as pd 
# from pandas.io.json import json_normalize #package for flattening json in pandas df

# #load json object
# with open(data) as f:
#     d = json.load(f)

# #lets put the data into a pandas df
# gd = pd.json_normalize(d)
# gd.head(3)

In [13]:
# from glom import glom
# # df = pd.read_json('data/nested_deep.json')
# # df['students'].apply(lambda row: glom(row, 'grade.math'))

In [41]:
games_df = df.loc[:,['name','required_age', 'is_free','review_score']]
games_df = games_df.head(10)
games_df

                                   name required_age is_free review_score
1198490        All That Remains: Part 1            0   False            0
1198510                       Paperball            0   False            8
1198550                        Moderium            0   False            0
1198600            Pizza Time Explosion            0   False            7
1198630            Customer Cums First!            0   False            7
1198700  Chained: A Victorian Nightmare            0   False            6
1198730                   Hentai Police            0   False            8
1198740                    Colony Siege            0   False            8
1198810                   Wolf and Pigs            0   False            0
1198820             Monster Girl Garden            0   False            5

In [42]:
# Importing sql library

from sqlalchemy import create_engine

In [45]:
# Create a reference for sql library

connection_string = 'sqlite:///game.db' 
engine = create_engine(connection_string, echo=False)

In [48]:
# Attach the data frame to the sql
games_df.to_sql('Gaming_Data',
                con = engine, if_exists="replace")

In [49]:
pd.read_sql('SELECT* FROM Gaming_Data', con = engine)

,index,name,required_age,is_free,review_score
0,1198490,All That Remains: Part 1,0,0,0
1,1198510,Paperball,0,0,8
2,1198550,Moderium,0,0,0
3,1198600,Pizza Time Explosion,0,0,7
4,1198630,Customer Cums First!,0,0,7
5,1198700,Chained: A Victorian Nightmare,0,0,6
6,1198730,Hentai Police,0,0,8
7,1198740,Colony Siege,0,0,8
8,1198810,Wolf and Pigs,0,0,0
9,1198820,Monster Girl Garden,0,0,5